### ISSUE TITLE
array parameterized with union type remains unhandled

### ISSUE THREAD

**Issue by joprice** [glutinum-org/cli#132]
Issue created from [Glutinum Tool](https://glutinum.net/#/editors/fsharp-code?typeScriptCode=ATCWDsBcFMCcDMCGBjawCC5QFtGVAPbgDS0AngGKyLZoDeAUCM8NIgM4QDmA-AFzB2kWN2AAfQcO4BtALrjgAV3AATaPAjQVAbiYtgBePHbRI-YOEXYARnAXpY1MgB5LNuxMsAbLwD4F3l4Kymoa4Fq6+gYADiigkGTmbrawAVYpcsGq6po6eizCiODs8ASw2OZCIuBcClUy8hIhOeF5IAC+DEA)

**Glutinum version -** 0.11.0-preview

**TypeScript**

```ts
  interface AnimationKeyFrame {
      easing?: string | string[] | undefined;
      offset?: number | Array<number | null> | null | undefined;
      opacity?: number | number[] | undefined;
      transform?: string | string[] | undefined;
  }

```

**FSharp**

```fs
module rec Glutinum

open Fable.Core
open Fable.Core.JsInterop
open System

[<AllowNullLiteral>]
[<Interface>]
type AnimationKeyFrame =
    abstract member easing: U2<string, ResizeArray<string>> option option with get, set
    abstract member offset: U2<float, Array<number | null>> option option with get, set
    abstract member opacity: U2<float, ResizeArray<float>> option option with get, set
    abstract member transform: U2<string, ResizeArray<string>> option option with get, set

```

**Problem description**

The type `Array<number | null>` remains unconverted from the original typescript type. I think the expected type would be `ResizeArray<float option>`.

**Comment by MangelMaxime** [comment]
This is because the type is read has a string `Array<number | null>`

![CleanShot 2024-10-06 at 16 05 52](https://github.com/user-attachments/assets/6aba011d-1a28-4f4c-9b44-06aeea352492)

Need to dig into improving the `TypeReference` support if possible or make the replacement rules working for types starting with `Array<`.

The reason it is read as string `Array<number | null>` is because we need to limit how me read types when dealing with recursive types otherwise, we end up in an infinite loop in the reader
